### ISSUE TITLE
could not connect to tracker (UDP)

### ISSUE THREAD

**Issue by olemaire** [naim94a/udpt#20]
my udpt is running with this configuration file regarding tracker and apiserver:
```
[tracker]
is_dynamic=1
port=6203
threads=5
allow_remotes=1
allow_iana_ips=0
announce_interval=60
cleanup_interval=120

[apiserver]
enable=1
threads=1
port=6203
```
When I remotely create a torrent, placing udp://<mytracker_IP>:6203/announce, my BT client (Transmission) is reporting "could not connect to tracker" 

I can see TCP/6203 is listening on my server running udpt (netstat -tanp|grep -i listen | grep 6203 - cool
But when I try to test UDP/6203, seems it's not binded:
```
blowjog@blowjog:/mnt/dcpbank/tracker/build/udpt$ nc -vnzu 127.0.0.1 6203
(UNKNOWN) [127.0.0.1] 6203 (?) : Connection refused

```
As I've got no log (see #19 ), this is the only way I did find to test - do I did something wrong?

TIA for any answer :)

Cheers,
-- 
lem

**Comment by naim94a** [comment]
Binding on udp won't show "LISTEN" state, since it's a stateless protocol (If you remove grep LISTEN, you should be able to find udpt bound on udp/6203).
I didn't get the error you are getting with nc (I get the "Connection succeeded") - I'm can't help if I don't get the same error.
Please note that if you are going to run a tracker locally, you should enable "allow_iana_ips".
